name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - release
      - 'feature/*'
  pull_request:
    branches:
      - develop
      - release
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Common Build Step
        run: echo "Running common build job for branch ${{ github.ref_name }}"

  deploy-dev:
    if: github.event_name == 'push' && startsWith(github.ref_name, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        run: echo "Deploying feature branch ${{ github.ref_name }} to Dev environment"

  deploy-uat:
    if: github.event_name == 'push' && github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to UAT
        run: echo "Deploying develop branch to UAT environment "

  deploy-prod:
    if: github.event_name == 'push' && github.ref_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Prod
        run: echo "Deploying release branch to Production environment"
